<table border="0" cellpadding="0" cellspacing="0" align="center" width="760"><tr><td>
  <img src="<%=request.getContextPath()%>/img/header1.gif" />
  <br/><br/><hr/>
  <table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td align="center">
    <a href="<%=request.getContextPath()%>/index.jsp">Home</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="<%=request.getContextPath()%>/readme.txt">Readme</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="<%=request.getContextPath()%>/javadocs/index.html">Javadocs</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="<%=request.getContextPath()%>/history.txt">History</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="<%=request.getContextPath()%>/license.txt">License</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="<%=request.getContextPath()%>/contributors.txt">Contributors</a>
  </td></tr></table>
  <hr/><br/>
